### ISSUE TITLE
I think v0.9.4 font size is very small.

### ISSUE THREAD

**Issue by johe123qwe** [treymo/joplin-link-graph#20]

**Comment by treymo** [comment]
You can zoom in and out of the graph.  Are you referring to the text of an individual node or the title/button?

**Comment by atn-journal** [comment]
Hey! I think he was referring to the text of an individual node, I ended up here by looking for a solution. Of course I could zoom in, but in order to have a "bigger picture" it would be nice to be able to read the nodes when I'm not that immersed in the graph.

Also, in order to identify target notedes to watch for, i.e. nodes with lots of connections, I'd like for the lines and nodes (the figures, not the names) to be more noticeable. As you can appreciate in the following image, i can barely see anything when zooming out (and again, zooming out —at least to me— is super-relevant).

![image](https://user-images.githubusercontent.com/53961590/116915470-7105c080-ac22-11eb-8c21-9271e05cce43.png)

This is my first interaction at Github, so let me know if maybe I should post this somewhere else. Thanks for this great plugin!

**Comment by treymo** [comment]
I understand what you mean about the node font size.  I'll see if I can add a setting for this as a starting point and maybe make it a more friendly UI button or something when I have time.

As for your second feature, I don't really follow what you mean.  Do you want a way to identify which node has a large number of connection even if it's not the currently selected node?

**Comment by atn-journal** [comment]
Thank you!

About the second feature, yes. I mean, visually identification. I'd like to see every node and it's connections when I'm positioned "away". I like that the selected node is emphasized, but the non-selected nodes are barely noticeable, as you can see in the picture.

**Comment by treymo** [comment]
I've having some issues getting the graph to redraw when I change the CSS/styling of the font.  Not really sure what's wrong with my branch but I can push it up and as laurent for some assitance

**Comment by treymo** [comment]
So you can adjust the node font size in the Graph UI plugin settings, but because of the issue mentioned above, it requires a restart of Joplin to take effect
